apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-windows-config
  labels:
    app: fluent-bit-windows
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              C:\\var\\log\\containers\\*.log
        Parser            docker
        DB                /var/log/flb_kube1.db
        Skip_Long_Lines   On
        Refresh_Interval  60

    [INPUT]
        Name              tail
        Tag               iis.*
        Path              C:\\var\\log\\iis\\**\\*.log,C:\\var\\log\\iis\\*.log
        Parser            iis
        DB                /var/log/flb_iis.db
        Skip_Long_Lines   On
        Refresh_Interval  60

    [INPUT]
        Name              winlog
        Channels          Setup,Windows PowerShell,Application,System,Security
        Interval_Sec      60
        DB                winlog.sqlite


    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Kube_Tag_Prefix     kube.c.var.log.containers.

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_Under        kubernetes

    # [OUTPUT]
    #     Name          syslog
    #     Match          *
    #     Host          OUTPUT-ADDRESS
    #     Port          OUTPUT-PORT
    #     Mode          MODE  
    #     syslog_format rfc5424
    #     Syslog_Hostname_key  host
    #     Syslog_Appname_key   pod_name
    #     Syslog_Procid_key    container_name
    #     Syslog_Message_key   log

    [OUTPUT]
        Name          file
        Match         *
        Path          /tmp/output.txt
  
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
    [PARSER]
        Name        iis
        Format      regex
        Regex       /(?<time>\d{4}-\d{2}-\d{2} [\d:]+) (?<message>.+)/
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: fluent-bit-windows
  name: fluent-bit-windows
  namespace: pks-system
spec:
  selector:
    matchLabels:
      app: fluent-bit-windows
  template:
    metadata:
      labels:
        app: fluent-bit-windows
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: "NoSchedule"
      containers:
      - image: fluent-bit-1.9
        imagePullPolicy: IfNotPresent
        name: fluent-bit
        volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: false
        - mountPath: /fluent-bit/etc
          name: fluent-bit-windows-config
        - mountPath: "E:"
          name: rootcontainers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: rootcontainers
        hostPath:
          path: E:/
      - configMap:
          defaultMode: 420
          name: fluent-bit-windows-config                                       
        name: fluent-bit-windows-config
      serviceAccountName: fluent-bit-win
  updateStrategy:
    type: RollingUpdate