apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-f461
  labels:
    app: hello-world-f461
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-f461
  template:
    metadata:
      labels:
        app: hello-world-f461
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      volumes:
      - name: dump-data
        emptyDir: {}
      - name: varlog
        hostPath:
          path: /var/log 
      tolerations:
      - key: "windows"
        operator: "Equal"
        value: "2019"
        effect: "NoSchedule"
      containers:
      - name: hello-world-f461
        image: kjsimages.azurecr.io/hello-world-aspnet-f461:0.2
        ports:
        - containerPort: 5050
        volumeMounts:
          - name: dump-data
            mountPath: /dmp
          - name: varlog
            mountPath: "/var/log/"
        resources:
          requests:
            cpu: 250m
            memory: 4Gi
          limits:
            cpu: 500m
            memory: 5Gi
      imagePullSecrets:
      - name: kjs-acr-pullsecret
---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-f461-svc
  labels:
    app: hello-world-f461
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
  selector:
    app: hello-world-f461
  type: LoadBalancer